language: python
python:
  - "3.6"

before_install:
  - pip install codecov
  - pip install -U pytest
  - pip install attrs==21.2.0
  - pip install pytest-cov


install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest --cov quantel tests/

after_success:
  - codecov