language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"

before_install:
  - pip install codecov
  - pip install pytest==6.2.4
  - pip install attrs==21.2.0
  - pip install pytest-cov

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=./

after_success:
  - codecov